const spells = [
  {
    name: "Alohomora",
    description: "Unlocks doors and locks.",
    difficulty: 0,
    type: "Enchantment",
    color: "#ADD8E6",
    effect: "Unlocks locked doors and windows.",
    continuum: false,
  },
  {
    name: "Expelliarmus",
    description: "Disarms the opponent.",
    difficulty: 1,
    type: "Defense Spell",
    color: "#FF0000",
    effect: "Causes the wand or object in the opponent's hand to be ripped out.",
    continuum: false,
    path: [
      [0.2, 0],
      [0, -0.2],
    ],
  },
  {
    name: "Expecto Patronum",
    description: "Summons a Patronus to ward off Dementors.",
    difficulty: 2,
    type: "Defense Enchantment",
    color: "#0099FF",
    effect: "Summons a Patronus (corporeal or incorporeal) that wards off Dementors and Lethifolds.",
    continuum: false,
  },
  {
    name: "Accio",
    description: "Attracts objects to the wizard.",
    difficulty: 1,
    type: "Summoning Enchantment",
    color: "#008000",
    effect: "Brings the mentioned object to the wizard.",
    continuum: false,
  },
  {
    name: "Wingardium Leviosa",
    description: "Makes objects levitate.",
    difficulty: 0,
    type: "Enchantment",
    color: "#D8BFD8",
    effect: "Allows the wizard to levitate objects.",
    continuum: false,
  },
  {
    name: "Stupefy",
    description: "Stuns the target.",
    difficulty: 1,
    type: "Offensive Spell",
    color: "#FF0000",
    effect: "Immobilizes and stuns the target.",
    continuum: false,
  },
  {
    name: "Obliviate",
    description: "Erases specific memories.",
    difficulty: 2,
    type: "Enchantment",
    color: "#FFFFE0",
    effect: "Modifies or erases specific memories from the target.",
    continuum: false,
  },
  {
    name: "Avada Kedavra",
    description: "Causes instant death to the target.",
    difficulty: 3,
    type: "Unforgivable Curse",
    color: "#00ff00",
    effect: "Instant death, without causing pain.",
    continuum: false,
  },
  {
    name: "Crucio",
    description: "Causes intense pain to the target.",
    difficulty: 3,
    type: "Unforgivable Curse",
    color: "#FF0000",
    effect: "Inflicts extreme pain, without causing permanent physical damage.",
    continuum: false,
  },
  {
    name: "Imperio",
    description: "Controls the target's mind.",
    difficulty: 3,
    type: "Unforgivable Curse",
    color: "#E5E4E2",
    effect: "Allows the caster to control the target's actions.",
    continuum: true,
  },
  {
    name: "Sectumsempra",
    description: "Cuts the target like an invisible blade.",
    difficulty: 2,
    type: "Offensive Spell",
    color: "#FF0000",
    effect: "Causes deep cuts on the target.",
    continuum: false,
  },
  {
    name: "Riddikulus",
    description: "Transforms a Boggart into something funny.",
    difficulty: 1,
    type: "Defense Enchantment",
    color: "#E5E4E2",
    effect: "Turns the Boggart into something comical to weaken it.",
    continuum: false,
  },
  {
    name: "Expulso",
    description: "Causes an explosion.",
    difficulty: 1,
    type: "Explosive Enchantment",
    color: "#0000FF",
    effect: "Creates an explosion on the target.",
    continuum: false,
  },
  {
    name: "Petrificus Totalus",
    description: "Completely immobilizes the target.",
    difficulty: 1,
    type: "Paralysis Spell",
    color: "#ADD8E6",
    effect: "Immobilizes the target, leaving them conscious.",
    continuum: false,
  },
  {
    name: "Aguamenti",
    description: "Conjures a jet of water.",
    difficulty: 0,
    type: "Enchantment",
    color: "#ADD8E6",
    effect: "Creates a jet of water from the wand.",
    continuum: false,
  },
  {
    name: "Reducto",
    description: "Destroys solid objects.",
    difficulty: 1,
    type: "Destruction Spell",
    color: "#0000FF",
    effect: "Reduces the target to dust or fragments.",
    continuum: false,
  },
  {
    name: "Lumos Solem",
    description: "Creates a strong beam of light from the wand.",
    difficulty: 1,
    type: "Enchantment",
    color: "#FFFFFF",
    effect: "Generates sunlight, used against creatures like Devil's Snare.",
    continuum: true,
  },
  {
    name: "Lumos Maxima",
    description: "Creates a Ball of Light that can brighten a room for a long period time.",
    difficulty: 1,
    type: "Enchantment",
    color: "#FFFFFF",
    effect: "Generates intense light, used to light up rooms.",
    continuum: true,
  },
  {
    name: "Diffindo",
    description: "Cuts objects.",
    difficulty: 1,
    type: "Slashing Spell",
    color: "#FF0000",
    effect: "Cuts or separates objects like fabrics and ropes.",
    continuum: false,
  },
  {
    name: "Finite Incantatem",
    description: "Cancels ongoing spells.",
    difficulty: 1,
    type: "Annulment Enchantment",
    color: "#FFF",
    effect: "Nullifies active spells or enchantments.",
    continuum: false,
  },
  {
    name: "Incendio",
    description: "Conjures fire.",
    difficulty: 0,
    type: "Fire Spell",
    color: "#FFA500",
    effect: "Creates flames on the target.",
    continuum: false,
  },
  {
    name: "Levicorpus",
    description: "Suspends the target by the ankle.",
    difficulty: 2,
    type: "Levitation Spell",
    color: "#FFF",
    effect: "Suspends the target in the air upside down.",
    continuum: false,
  },
  {
    name: "Muffliato",
    description: "Prevents others from hearing conversations.",
    difficulty: 1,
    type: "Spell",
    color: "#FFF",
    effect: "Creates a buzzing in the ears of others, preventing them from hearing conversations.",
    continuum: false,
  },
  {
    name: "Protego Horribilis",
    description: "Creates a protective barrier against Dark spells.",
    difficulty: 2,
    type: "Defense Spell",
    color: "#50C878",
    effect: "Creates a magical barrier against Dark spells.",
    continuum: false,
  },
  {
    name: "Bombarda Maxima",
    description: "Creates a big explosion.",
    difficulty: 2,
    type: "Explosive Enchantment",
    color: "#FF00FF",
    effect: "Explodes doors, walls, and other objects.",
    continuum: false,
  },
  {
    name: "Bombarda",
    description: "Creates a small explosion.",
    difficulty: 1,
    type: "Explosive Enchantment",
    color: "#0000FF",
    effect: "Explodes doors, walls, and other objects.",
    continuum: false,
  },
  {
    name: "Relashio",
    description: "Free the target from a grip or chain.",
    difficulty: 1,
    type: "Spell",
    color: "#008000",
    effect: "Causes the target to release what it is holding.",
    continuum: false,
  },
  {
    name: "Silencio",
    description: "Silences the target.",
    difficulty: 1,
    type: "Enchantment",
    color: "#FFF",
    effect: "Makes the target unable to produce sound.",
    continuum: false,
  },
  {
    name: "Confringo",
    description: "Creates an intense explosion.",
    difficulty: 2,
    type: "Explosive Enchantment",
    color: "#FFA500",
    effect: "Causes the target to explode in flames.",
    continuum: false,
  },
  {
    name: "Obscuro",
    description: "Places a magical blindfold over the target's eyes.",
    difficulty: 1,
    type: "Restriction Spell",
    color: "#000",
    effect: "Temporarily blinds the target.",
    continuum: false,
  },
  {
    name: "Lumos",
    description: "Illuminates the tip of the wand.",
    difficulty: 0,
    type: "Enchantment",
    color: "#F0F0F0",
    effect: "Generates light at the tip of the wand.",
    continuum: true,
  },
  {
    name: "Nox",
    description: "Extinguishes the light generated by the Lumos spell.",
    difficulty: 0,
    type: "Enchantment",
    color: "#00a2aa",
    effect: "Extinguishes the light produced by Lumos.",
    continuum: false,
  },
  {
    name: "Protego",
    description: "Creates a protective shield.",
    difficulty: 1,
    type: "Defense Spell",
    color: "#0000FF",
    effect: "Blocks spells cast against the wizard.",
    continuum: false,
  },
];

export default spells;
